### PR TITLE
Fix Notice

### PR DESCRIPTION
**Pull request by bunke**

### CODE REVIEW

**Comment by agoalofalife** [comment]
@bunke  suppressing errors is not a good idea
You can try this option
```php
if (ob_get_length()) ob_clean();
```
or in file php.ini update parameter 
`output_buffering = 4096`

**Comment by agoalofalife** [comment]
@bunke did you check it works for you?

**Comment by bunke** [comment]
Yes, it works!

**Comment by agoalofalife** [comment]
@bunke thanks

**Pull request merged**
